import type { DesignSystem } from "@/types"

export const mockDesignSystem: DesignSystem = {
  archetype: {
    name: "dashboard",
    confidence: 0.82,
    reasoning:
      "High spec count (29) with deep hierarchy (8 levels), web dashboard component, monitoring patterns",
  },
  palette: {
    name: "default",
    description:
      "Professional blue — conveys trust, precision, and technical authority",
    vibe: ["professional", "trustworthy", "clean"],
    reference: "Think GitHub's interface — professional blue with clear hierarchy",
    primary: "#2563eb",
    secondary: "#64748b",
    accent: "#7c3aed",
    neutral: "#475569",
    semantic: {
      success: "#15803d",
      warning: "#b45309",
      error: "#dc2626",
      info: "#0369a1",
    },
    shades: [
      "#eff6ff",
      "#dbeafe",
      "#bfdbfe",
      "#93c5fd",
      "#60a5fa",
      "#3b82f6",
      "#2563eb",
      "#1d4ed8",
      "#1e40af",
      "#1e3a8a",
    ],
  },
  dark_mode: {
    background: "#0f172a",
    foreground: "#f8fafc",
    primary: "#3b82f6",
    shades: [
      "#1e293b",
      "#1e3a5f",
      "#1e40af",
      "#2563eb",
      "#3b82f6",
      "#60a5fa",
      "#93c5fd",
      "#bfdbfe",
      "#dbeafe",
      "#eff6ff",
    ],
    semantic: {
      success: "#22c55e",
      warning: "#f59e0b",
      error: "#ef4444",
      info: "#38bdf8",
    },
  },
  type_scale: {
    ratio: 1.25,
    level_count: 6,
    body_size: 14,
    sizes: [11, 12, 14, 16, 20, 24],
    line_heights: [1.4, 1.4, 1.5, 1.5, 1.3, 1.2],
    font_weights: [400, 500, 600],
    font_family: "'Inter', system-ui, sans-serif",
  },
  spacing: {
    base: 4,
    ratio: 2,
    step_count: 8,
    steps: [4, 8, 12, 16, 24, 32, 48, 64],
  },
  component_styles: {
    button_border_radius: 6,
    card_border_radius: 8,
  },
  layout: {
    sidebar: {
      position: "left",
      width: "240px",
      nav_items: [
        "Overview",
        "Validate",
        "Watch",
        "Format",
        "Graph",
        "Coverage",
        "Settings",
      ],
    },
    header: { title: "Minter", has_search: true },
    content: {
      sections: [
        { kind: "metric-cards", title: "Overview", width: "full" },
        { kind: "data-table", title: "Specifications", width: "full" },
        { kind: "status-panel", title: "Validation", width: "half" },
      ],
    },
  },
  spec_metadata: {
    project_name: "Minter",
    domains: [
      {
        name: "Core Commands",
        spec_count: 11,
        spec_names: [
          "validate-command",
          "watch-command",
          "format-command",
          "scaffold-command",
          "inspect-command",
          "graph-command",
          "guide-command",
          "coverage-command",
          "lock-command",
          "ci-command",
          "web-command",
        ],
      },
      {
        name: "Grammar",
        spec_count: 2,
        spec_names: ["spec-grammar", "nfr-grammar"],
      },
      {
        name: "MCP",
        spec_count: 3,
        spec_names: [
          "mcp-server",
          "mcp-response-format",
          "mcp-agent-guidance",
        ],
      },
      {
        name: "Design",
        spec_count: 5,
        spec_names: [
          "design-system-generator",
          "design-palette",
          "design-typography",
          "design-layout",
          "design-chat",
        ],
      },
      {
        name: "Infrastructure",
        spec_count: 8,
        spec_names: [
          "dependency-resolution",
          "graph-cache",
          "nfr-cross-validation",
          "file-discovery",
          "error-handling",
          "output-format",
          "cli",
          "explain-command",
        ],
      },
    ],
    spec_metrics: [
      { name: "validate-command", version: "2.1.0", behavior_count: 30 },
      { name: "cli", version: "2.4.0", behavior_count: 31 },
      { name: "spec-grammar", version: "1.3.0", behavior_count: 57 },
      { name: "nfr-grammar", version: "1.2.0", behavior_count: 42 },
      { name: "watch-command", version: "1.1.0", behavior_count: 18 },
      { name: "format-command", version: "1.0.0", behavior_count: 22 },
      { name: "scaffold-command", version: "1.0.0", behavior_count: 15 },
      { name: "inspect-command", version: "1.0.0", behavior_count: 12 },
      { name: "graph-command", version: "1.1.0", behavior_count: 19 },
      { name: "mcp-server", version: "1.2.0", behavior_count: 35 },
      { name: "dependency-resolution", version: "1.0.0", behavior_count: 28 },
      { name: "graph-cache", version: "1.1.0", behavior_count: 24 },
      { name: "design-system-generator", version: "1.0.0", behavior_count: 45 },
    ],
    total_spec_count: 29,
    total_behavior_count: 653,
    total_entity_count: 14,
  },
  decisions: [],
}
